//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingaporeFlorist.SingaporeFlorist {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SingaporeFlorist.IWsFreshFlowers")]
    public interface IWsFreshFlowers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsFreshFlowers/GetAllAccount", ReplyAction="http://tempuri.org/IWsFreshFlowers/GetAllAccountResponse")]
        System.Data.DataSet GetAllAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsFreshFlowers/GetAllAccount", ReplyAction="http://tempuri.org/IWsFreshFlowers/GetAllAccountResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllAccountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsFreshFlowers/GetProductDetails", ReplyAction="http://tempuri.org/IWsFreshFlowers/GetProductDetailsResponse")]
        System.Data.DataSet GetProductDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsFreshFlowers/GetProductDetails", ReplyAction="http://tempuri.org/IWsFreshFlowers/GetProductDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetProductDetailsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsFreshFlowersChannel : SingaporeFlorist.IWsFreshFlowers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsFreshFlowersClient : System.ServiceModel.ClientBase<SingaporeFlorist.IWsFreshFlowers>, SingaporeFlorist.IWsFreshFlowers {
        
        public WsFreshFlowersClient() {
        }
        
        public WsFreshFlowersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsFreshFlowersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsFreshFlowersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsFreshFlowersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllAccount() {
            return base.Channel.GetAllAccount();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllAccountAsync() {
            return base.Channel.GetAllAccountAsync();
        }
        
        public System.Data.DataSet GetProductDetails() {
            return base.Channel.GetProductDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetProductDetailsAsync() {
            return base.Channel.GetProductDetailsAsync();
        }
    }
}
