//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingaporeFloristNS.SingaporeFloristWs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SingaporeFloristWs.ISingaporeFloristWS")]
    public interface ISingaporeFloristWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingaporeFloristWS/GetAllProduct", ReplyAction="http://tempuri.org/ISingaporeFloristWS/GetAllProductResponse")]
        System.Data.DataSet GetAllProduct();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingaporeFloristWS/GetAllProduct", ReplyAction="http://tempuri.org/ISingaporeFloristWS/GetAllProductResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllProductAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingaporeFloristWS/GetAllOrders", ReplyAction="http://tempuri.org/ISingaporeFloristWS/GetAllOrdersResponse")]
        System.Data.DataSet GetAllOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingaporeFloristWS/GetAllOrders", ReplyAction="http://tempuri.org/ISingaporeFloristWS/GetAllOrdersResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingaporeFloristWS/GetAllDelivery", ReplyAction="http://tempuri.org/ISingaporeFloristWS/GetAllDeliveryResponse")]
        System.Data.DataSet GetAllDelivery();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingaporeFloristWS/GetAllDelivery", ReplyAction="http://tempuri.org/ISingaporeFloristWS/GetAllDeliveryResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllDeliveryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingaporeFloristWS/getAllInvoice", ReplyAction="http://tempuri.org/ISingaporeFloristWS/getAllInvoiceResponse")]
        System.Data.DataSet getAllInvoice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingaporeFloristWS/getAllInvoice", ReplyAction="http://tempuri.org/ISingaporeFloristWS/getAllInvoiceResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAllInvoiceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISingaporeFloristWSChannel : SingaporeFloristNS.SingaporeFloristWs.ISingaporeFloristWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SingaporeFloristWSClient : System.ServiceModel.ClientBase<SingaporeFloristNS.SingaporeFloristWs.ISingaporeFloristWS>, SingaporeFloristNS.SingaporeFloristWs.ISingaporeFloristWS {
        
        public SingaporeFloristWSClient() {
        }
        
        public SingaporeFloristWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SingaporeFloristWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingaporeFloristWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingaporeFloristWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllProduct() {
            return base.Channel.GetAllProduct();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllProductAsync() {
            return base.Channel.GetAllProductAsync();
        }
        
        public System.Data.DataSet GetAllOrders() {
            return base.Channel.GetAllOrders();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllOrdersAsync() {
            return base.Channel.GetAllOrdersAsync();
        }
        
        public System.Data.DataSet GetAllDelivery() {
            return base.Channel.GetAllDelivery();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllDeliveryAsync() {
            return base.Channel.GetAllDeliveryAsync();
        }
        
        public System.Data.DataSet getAllInvoice() {
            return base.Channel.getAllInvoice();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAllInvoiceAsync() {
            return base.Channel.getAllInvoiceAsync();
        }
    }
}
